# Generated by Django 5.2.17 on 2026-09-09 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "dept",
                    models.CharField(
                        blank=True,
                        help_text="For example: BGE",
                        max_length=60,
                        verbose_name="Department",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True,
                        help_text="For example: 2005-06",
                        max_length=20,
                        verbose_name="Session",
                    ),
                ),
                (
                    "is_past_student",
                    models.BooleanField(default=False, verbose_name="Past student"),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="DayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "youtube",
                    models.CharField(
                        choices=[("N", "No"), ("W", "Study or work"), ("Y", "Yes")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        choices=[("N", "No"), ("W", "Study or work"), ("Y", "Yes")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        choices=[("N", "No"), ("W", "Study or work"), ("Y", "Yes")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "news",
                    models.CharField(
                        choices=[("N", "No"), ("W", "Study or work"), ("Y", "Yes")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "other",
                    models.CharField(
                        choices=[("N", "No"), ("W", "Study or work"), ("Y", "Yes")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "watching",
                    models.CharField(
                        choices=[("N", "No"), ("W", "Study or work"), ("Y", "Yes")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "said_no",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Times you stopped yourself"
                    ),
                ),
                (
                    "instead",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="What you did instead"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Reason"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tracker.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "date"), name="one_log_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveSmallIntegerField()),
                (
                    "hardest",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="What was hardest"
                    ),
                ),
                (
                    "easier",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="What got easier"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="tracker.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "week"), name="one_note_per_week"
                    )
                ],
            },
        ),
    ]
