# Generated by Django 5.2.17 on 2026-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_seed_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_organiser",
            field=models.BooleanField(
                default=False,
                help_text="Runs the challenge instead of competing: kept off the board, and can read everyone's notes.",
                verbose_name="Organiser",
            ),
        ),
    ]
