# Generated by Django 5.2.17 on 2026-09-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_split_organiser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="daylog",
            name="evidence",
            field=models.ImageField(
                blank=True,
                help_text="Optional. A screenshot of the video, article or page, if you want to show it.",
                upload_to="evidence/%Y/%m/",
                verbose_name="Screenshot",
            ),
        ),
    ]
