# Generated by Django 5.2.17 on 2026-09-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_daylog_evidence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daylog",
            name="evidence",
        ),
    ]
