# Generated by Django 5.2.17 on 2026-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_remove_daylog_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="daylog",
            name="messaging",
            field=models.CharField(
                choices=[("N", "No"), ("C", "Communication only"), ("Y", "Others")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="facebook",
            field=models.CharField(
                choices=[
                    ("N", "No"),
                    ("C", "Communication only"),
                    ("W", "Study or work"),
                    ("Y", "Yes"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="instagram",
            field=models.CharField(
                choices=[
                    ("N", "No"),
                    ("C", "Communication only"),
                    ("W", "Study or work"),
                    ("Y", "Yes"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="news",
            field=models.CharField(
                choices=[
                    ("N", "No"),
                    ("C", "Communication only"),
                    ("W", "Study or work"),
                    ("Y", "Yes"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="other",
            field=models.CharField(
                choices=[
                    ("N", "No"),
                    ("C", "Communication only"),
                    ("W", "Study or work"),
                    ("Y", "Yes"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="watching",
            field=models.CharField(
                choices=[
                    ("N", "No"),
                    ("C", "Communication only"),
                    ("W", "Study or work"),
                    ("Y", "Yes"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="daylog",
            name="youtube",
            field=models.CharField(
                choices=[
                    ("N", "No"),
                    ("C", "Communication only"),
                    ("W", "Study or work"),
                    ("Y", "Yes"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
